[project]
name = "WebSpider"
version = "0.1.1"
description = "Default template for PDM package"
authors = [
    {name = "inkicchj", email = "399434428@qq.com"},
]
dependencies = []
requires-python = "==3.13.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
